version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_desafio
    restart: always
    ports:
      - "6379:6379"
    networks:
      - desafio_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_desafio
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - desafio_network

  api:
    build: ./app
    container_name: api_desafio
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - desafio_network

  worker:
    build: ./worker
    container_name: worker_desafio
    restart: always
    depends_on:
      - redis
      - rabbitmq
    networks:
      - desafio_network

networks:
  desafio_network:
    driver: bridge
